// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBriJILf1-_SWajkEiflxbyGcK-tNIWcf8',
    appId: '1:741624385103:web:93a09120f939e10054643a',
    messagingSenderId: '741624385103',
    projectId: 'myinterior-9f364',
    authDomain: 'myinterior-9f364.firebaseapp.com',
    databaseURL: 'https://myinterior-9f364-default-rtdb.firebaseio.com',
    storageBucket: 'myinterior-9f364.appspot.com',
    measurementId: 'G-3TLR6DL5X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9LLHH03sZzfYRMIPdl7yEn06zxSw8-kg',
    appId: '1:741624385103:android:0c4c7c68fb8dcd2254643a',
    messagingSenderId: '741624385103',
    projectId: 'myinterior-9f364',
    databaseURL: 'https://myinterior-9f364-default-rtdb.firebaseio.com',
    storageBucket: 'myinterior-9f364.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeWnVO4pc79nZwqbfOWgzg85cd2q7wS1g',
    appId: '1:741624385103:ios:7144a06005fc29b654643a',
    messagingSenderId: '741624385103',
    projectId: 'myinterior-9f364',
    databaseURL: 'https://myinterior-9f364-default-rtdb.firebaseio.com',
    storageBucket: 'myinterior-9f364.appspot.com',
    iosClientId: '741624385103-llac3hhf0oesju7spn1lmkcon4fbq8co.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBlocDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeWnVO4pc79nZwqbfOWgzg85cd2q7wS1g',
    appId: '1:741624385103:ios:7144a06005fc29b654643a',
    messagingSenderId: '741624385103',
    projectId: 'myinterior-9f364',
    databaseURL: 'https://myinterior-9f364-default-rtdb.firebaseio.com',
    storageBucket: 'myinterior-9f364.appspot.com',
    iosClientId: '741624385103-llac3hhf0oesju7spn1lmkcon4fbq8co.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBlocDemo',
  );
}
